### ISSUE TITLE
Memory leak when using MLX models

### ISSUE THREAD

**Issue by Me1000** [lmstudio-ai/mlx-engine#36]
When I load Qwen Coder 2.5 32B Q4 MLX (8k context) it uses about 17.3GB of RAM. After a while it's consuming over 40GB. LM Studio doesn't report the memory usage ever going down until I eject the model and reload it. Then it goes back to 17GB.

This is happening on LMStudio 0.3.5 the v0.0.14 of the mlx runtime on an M4 Max MacBook Pro.

Please let me know if there is anything else you need from me to debug this issue.

**Comment by neilmehta24** [comment]
Hello, thanks for the report. This will be fixed in the next version on LM Studio.

Similar issue: https://github.com/lmstudio-ai/mlx-engine/issues/18

**Comment by neilmehta24** [comment]
> now MLX is 50% slower than GGUF.

We are tracking this issue in #55, and we have a performance fix ready in #52. Note that this fix will improve MLX performance, but you may still observe the GGUF is faster. If you do, please let us know so that we can see if there are further optimizations we can make in `mlx_lm`.

I am closing this issue, please track further updates in #55
