### ISSUE TITLE
Unable to load Mistral-Nemo fine tune 4-bit / float 32 mlx_lm quantized

### ISSUE THREAD

**Issue by chimezie** [lmstudio-ai/mlx-engine#53]
Version 0.3.5 Build 8

## Model ##
A model of my own, running on the latest mlx/mlx-lm as of the time of this, built from git source and used to quantize the model.  The model was fine-tuned from Nemo Mistral and fused using mlx_lm.  I can prompt in the CL via mlx_lm.generate --prompt ".. prompt .." --model [.. path ..] 

## Transformers version ##
```commandline
% pip freeze | grep transformers
transformers==4.46.3
```

## Error I'm getting ##

>  'ArrayValue filter: rejectattr'

**Comment by neilmehta24** [comment]
Forgot to provide an update here. This issue is fixed in the latest beta release https://lmstudio.ai/beta-releases

**Comment by chimezie** [comment]
I just tried with that beta (0.3.5) and received the same error.  Is there something you need from me to get more information about the error?

**Comment by neilmehta24** [comment]
@chimezie could you please link the exact model that your finetune was derived from?

And can you confirm that the build number of your LM Studio install is `0.3.5 build 9`? You should see this version in the bottom left corner of the app.

I suspect the issue is related to this https://github.com/huggingface/huggingface.js/pull/988 . We expected build 9 of LM Studio to have deployed that fix.

**Comment by chimezie** [comment]
I tried this on a new Nemo fine-tune, quantized at 4 and 8 bits in latest mlx and was able to load it fine.  Thanks for you help and brilliant product.
